### PR TITLE
Reduce flakiness of Sync tests

### LINKED ISSUE #625: Flaky test `prop_syncBlocks_io_full`
```  
      prop_syncBlocks_io_full:                               FAIL (0.06s)
            ✗ prop_syncBlocks_io_full failed after 1 test.
                  ┏━━ test/Test/Oscoin/Protocol/Sync.hs ━━━
              234 ┃ prop_syncBlocks_io_full :: Dict (IsCrypto c) -> Property
              235 ┃ prop_syncBlocks_io_full d@Dict = withTests 1 . property $ do
                  ┃ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                  ┃ │ ━━━ Exception: SomeAsyncException ━━━
                  ┃ │ ExceptionInLinkedThread ThreadId 8126 Network.Socket.bind: resource busy (Address already in use)
              236 ┃     testPeer1@(peer1, chain1) <- forAll (genNakamotoPeer d)
              237 ┃     (peer2, _) <- forAll (genNakamotoPeer d)
              238 ┃     (peer3, _) <- forAll (genNakamotoPeer d)
              239 ┃
              240 ┃     let allBlocksNoGenesis = drop 1 $ Oscoin.Prelude.reverse (toNewestFirst $ blockschain1)
              241 ┃     let fullRange = fromJust $ range (nakamotoGenesis d) (tip chain1)
              242 ┃     let getActive = pure $ Set.fromList [peer1, peer2, peer3]
              243 ┃
              244 ┃     evts <- liftIO newTQueueIO
              245 ┃
              246 ┃     withNodes d [testPeer1, (peer2, chain1), (peer3, chain1)] $ do
              247 ┃         liftIO $ STM.withBlockStore chain1 Nakamoto.blockScore $ \(localChainReader,_) -> do
              248 ┃           syncContext <- IO.newSyncContext getActive localChainReader [atomically . writeTQueue evts] noProbe
              249 ┃           IO.runSync syncContext (Sync.syncBlocks fullRange)
              250 ┃
              251 ┃         allEvts <- liftIO $ atomically (flushTQueue evts)
              252 ┃         allEvts === map SyncBlock allBlocksNoGenesis
              This failure can be reproduced by running:
              > recheck (Size 0) (Seed 6600035671170785268 16015426828560870189) prop_syncBlocks_io_full
          Use '--hedgehog-replay "Size 0 Seed 6600035671170785268 16015426828560870189"' to reproduce.
```

### PR DESCRIPTION
**Pull request by adinapoli-mndc**
Fix #625. 

I have explained my line of reasoning in the comment of the new code, but in a nutshell in order to reduce the flakiness of the IO tests, we need to ensure that there is no collision when picking the HTTP ports. Randomness and `Hedgehog` generators doesn't help us, so I had to pull the `unsafePerformIO` cannon into the mix.

### CODE REVIEW

File: test/Test/Oscoin/Protocol/Sync.hs [hunk 1]
```diff
@@ -371,32 +382,68 @@ mockGenesis = defaultGenesis (Dict :: Dict (IsCrypto MockCrypto)) mempty
...
+-- parallel) to all succeed.
+
+-- | A global counter for the HTTP ports.
+--
+-- N.B. We start from 0 for a simple reason: in case we reach the maximum
+-- number of ports (i.e. maxBound :: Word16, i.e. 65535), the counter would
+-- overflow, starting from 0. However, we cannot bind to 0 (nor to a bunch of
+-- system-used ports). This is why in `nextUnusedHttpPort' we increment the
+-- counter by 1 but we return /port + 3000/: This ensure that in case of
+-- overflow we would resume back from an allowed range.
```
Comment (cloudhead) [inline test/Test/Oscoin/Protocol/Sync.hs]: Clever :+1:

Comment (adinapoli-mndc) [reply test/Test/Oscoin/Protocol/Sync.hs]: @cloudhead dude, go away! You shouldn't be coding (more so working) during a public holiday! 😉 😝
